### ISSUE TITLE
I set strategy "ONLY_REMOTE" , but actually  run with "ONLY_LOCAL" 3 times

### ISSUE THREAD

**Issue by fred3306** [aizuda/easy-retry#1]
您好，在运行demo场景”remoteRetryWithBizNo“时，设置retryStrategy = RetryType.ONLY_REMOTE，结果日志显示本地执行重试3次，
<img width="1406" alt="image" src="https://github.com/aizuda/easy-retry/assets/4034016/c852af90-8c70-4f43-9b64-65b3885d898d">

**Comment by byteblogs168** [comment]
感谢您的提的问题，这个问题会在下一个版本进行优化，谢谢关注

**Comment by byteblogs168** [comment]
已经在2.1.0版本实现了
