### ISSUE TITLE
关于服务端的

### ISSUE THREAD

**Issue by 2019hehe** [aizuda/easy-retry#4]
后续会支持Mysql以外的数据库吗？

**Comment by byteblogs168** [comment]
您好，目前您提这个问题已经在开发中了, 您希望支持哪些数据库呢?
https://gitee.com/aizuda/easy-retry/issues/I7Q2TS

**Comment by 2019hehe** [comment]
目前主流的就好，不过如果自行修改适配的话，修改的地方是否会涉及很多，以及更换数据库的话是否会对原有功能造成影响？

**Comment by byteblogs168** [comment]
目前已经考虑到扩展性，目前我们使用ORM框架是Mybatis Plus， MP已经支持几十种数据库这些EasyRetry也支持，只是有些在xml里面写的sql，有些数据库不支持，需要再具体的数据库模块实现即可，具体可以参考这个PG数据库的实现https://gitee.com/aizuda/easy-retry/blob/dev_2.2.0/easy-retry-datasource/easy-retry-postgres-datasource/src/main/resources/postgres/mapper/ServerNodeMapper.xml
